sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
  - python tests/check_titles.py
  - python tests/check_confs.py
  - mkdocs build -f mkdocs.yml
  - mkdocs build -f mkdocs_es.yml --clean
  - python tests/check_strings.py -v -l
