sudo: false
language: python
python:
  - "2.7"
install:
  - "export LC_ALL=en_US.UTF8"
  - "pip install --no-cache-dir -r requirements.txt"
  - "export PYTHONPATH=$PWD/sitecustomize"
script:
  - mkdocs build -f mkdocs.yml
  - mkdocs build -f mkdocs_es.yml --clean
  - python check_strings.py
