sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
script:
  - python check_titles.py
  - mkdocs build -f mkdocs.yml
  - mkdocs build -f mkdocs_es.yml --clean
  - python check_strings.py -v -l
