# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 2.7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7
      uses: actions/setup-python@v4
      with:
        python-version: "2.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and build
      run: |
        python tests/check_titles.py
        python tests/check_confs.py
        mkdocs build -f mkdocs.yml
        mkdocs build -f mkdocs_es.yml --clean
        python tests/check_strings.py -v -l