# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 2.7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 2
      run: |
        sudo apt update
        sudo apt install python2 python-pip
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
        printf '1\n' | sudo update-alternatives --config python
        cd /usr/bin
        sudo ln -s /usr/bin/pip2 ./pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and build
      run: |
        python tests/check_titles.py
        python tests/check_confs.py
        mkdocs build -f mkdocs.yml
        mkdocs build -f mkdocs_es.yml --clean
        python tests/check_strings.py -v -l